name: api

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  convex_dart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  collection: ^1.19.1
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  convex_dart_builder:
  faker: ^2.2.0
  recase: ^4.1.0

resolution: workspace
